name: talentVerse CD

on:
  workflow_run:
    workflows: ['talentVerse CI']
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy updated image to ECS
        run: |
          aws ecs update-service \
            --cluster talentverse-cluster \
            --service talentverse-service \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}